### ISSUE TITLE
TODO list for MVP

### ISSUE THREAD

**Issue by mattdavis0351** [mattdavis0351/day3api#1]
- [x] multi stage Dockerfile
- [x] route for []byte("string)
- [x] route for static html
- [x] route for struct -> JSON
- [x] create static site
